### PR TITLE
Needed changes to Xcode 8

### PR DESCRIPTION
**Pull request by fjtrujy**
Hello,
Basically I have added in the configuration plist the ID for Xcode 8, and also I have update to the recommended settings the project configuration.

Thanks.

### CODE REVIEW

**Comment by fjtrujy** [comment]
Hello did you take a look to this MR?

**Comment by benoitsan** [comment]
Hi Francisco, I'm missing something, plugins are deprecated with Xcode 8 and it should not work.

**Comment by fjtrujy** [comment]
Hello again,

You're right partially, Xcode 8 by default is not accepting the plugin, but there is a solution for that, is "Unsign" the Xcode. 
There is several process about how to do it, from my point of view the easiest one is:
https://github.com/fpg1503/MakeXcodeGr8Again

I have attached a screenshot with the Xcode 8 and the Alcatraz installed.

screen shot 2016-10-07 at 8 51 34 am 2


Thanks in advance,

**Comment by benoitsan** [comment]
Thanks for the clarification. That's what I thought… Since it's a "hack" I don't want to perform on my Mac, I couldn't build it, test it and so assuming the support of the plugin. For these reasons, I prefer to reject this pull request.

**Pull request closed without merging**
