### PR TITLE
Update to Uncrustify 0.61

### PR DESCRIPTION
**Pull request by sethfri**
PR for #77 

1. Downloaded zip of Uncrustify 0.61
2. Ran `./configure`
3. Ran `make`
4. Overwrote uncrustify binary in `BBUncrustifyPlugin-Xcode`

### CODE REVIEW

**Comment by benoitsan** [comment]
Thank you Seth. Appreciated.

**Comment by sethfri** [comment]
No problem, Benoît, thank you for the awesome plugin!

What do you think the ETA will be on a release including this update?

**Comment by benoitsan** [comment]
I will do it today.

**Comment by benoitsan** [comment]
Released ;) https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/releases/tag/2.0.5

**Comment by sethfri** [comment]
Fantastic! Thank you!

**Comment by jlerner** [comment]
Is it possible the wrong version of the binary snuck in somehow?

    $ UncrustifyPlugin.xcplugin/Contents/Resources/uncrustify -v
    uncrustify 0.60

**Pull request merged**
